name: fcps_pearls

description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  forui: ^0.10.0+1
  colornames: 
  flutter:
    sdk: flutter
  uuid: ^4.4.0
  floor: ^1.5.0
  floor_generator: ^1.5.0
  objectbox: ^4.2.0
  objectbox_flutter_libs: ^4.2.0
  objectbox_generator: ^4.2.0
  build_runner: ^2.4.15
  states_rebuilder: ^6.4.0
  flutter_native_splash: ^2.4.6
  manager:
    path: ..//manager
dev_dependencies:
  flutter_launcher_icons: ^0.14.1
flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
  windows:
    generate: true
    image_path: "assets/app_icon.png"
    icon_size: 48

flutter_native_splash:
  color: "#42a5f5"
  image: assets/app_icon.png
  ios: false
  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/
    # - shorebird.yaml
# dart run flutter_launcher_icons
# dart run flutter_native_splash:create
